version: 2.1
orbs:
  node: circleci/node@4.1.0
  eb: circleci/aws-elastic-beanstalk@1.0.0
  aws-cli: circleci/aws-cli@2.0.2
jobs:
  build:
    docker:
      - image: "cimg/base:stable"
    steps:
      - node/install
      - checkout
      - aws-cli/setup:
          profile-name: default
      - eb/setup
      - run:
          name: Install Backend Dendencies
          command: |
            npm run install:backend
      - run:
          name: Install Frontend Dendencies
          command: |
            npm run install:frontend
      - run:
          name: Build Backend Application
          command: |
            npm run build:backend
      - run:
          name: Build Frontend Application
          command: |
            npm run build:frontend
      - run:
          name: Deploy Backend Application
          command: |
            npm run deploy:backend
      - run:
          name: Deploy Frontend Application
          command: |
            npm run deploy:frontend
